### ISSUE TITLE
Milliseconds part in timestamp is not accurate.

### ISSUE THREAD

**Issue by kmrshntr** [embulk/embulk-output-bigquery#76] opened 2018-04-03 03:28 UTC
I tried this example.

https://github.com/embulk/embulk-output-bigquery/tree/v0.4.5#run-example

But,  the unexpected result came out as following:

![2018-04-03 11 00 00](https://user-images.githubusercontent.com/300862/38227037-3667f4b0-3737-11e8-80ae-bc03fd488a8f.png)

The milliseconds part of values in timestamp column in BQ are `.000` although the source timestamp column in [CSV]( https://github.com/embulk/embulk-output-bigquery/blob/master/example/example.csv) has microseconds part `.100000`.

This is my config.yml. I didn't change `in:` part of [the example.](https://github.com/embulk/embulk-output-bigquery/blob/master/example/config_replace.yml)
```
in:
  type: file
  path_prefix: example/example.csv
  parser:
    type: csv
    charset: UTF-8
    newline: CRLF
    null_string: 'NULL'
    skip_header_lines: 1
    comment_line_marker: '#'
    columns:
      - {name: date,        type: string}
      - {name: timestamp,   type: timestamp, format: "%Y-%m-%d %H:%M:%S.%N", timezone: "+09:00"}
      - {name: "null",      type: string}
      - {name: long,        type: long}
      - {name: string,      type: string}
      - {name: double,      type: double}
      - {name: boolean,     type: boolean}
out:
  type: bigquery
  mode: append
  auth_method: json_key
  json_keyfile: ****
  auto_create_table: true
  dataset: example_dataset
  table: example
```

### versions:
java: 1.8.0_162 ( oracle )
embulk: v0.9.4
bigquery plugin: v0.4.5

**Comment by kmrshntr** [comment] 2018-04-03 04:10
This issue is seems to be time formatting failure.
This is TRACE log of example. The microsecond parts are formatted to `.000100` even though the source them are `.100000`.

```
2018-04-03 10:57:16.640 +0900 [TRACE] (embulk-output-executor-3): embulk-output-bigquery: record ["2015-07-13", 2015-07-12 15:00:00 UTC, "", 93, "KjCRAc-A", 477.4, true]
2018-04-03 10:57:16.640 +0900 [TRACE] (embulk-output-executor-2): embulk-output-bigquery: record ["2015-07-13", 2015-07-12 15:00:00 UTC, "", 92, "0hgDRI_m", 810.9, true]
2018-04-03 10:57:16.640 +0900 [TRACE] (embulk-output-executor-0): embulk-output-bigquery: record ["2015-07-13", 2015-07-12 15:00:00 UTC, "", 90, "l6lTsvxd", 903.4, true]
2018-04-03 10:57:16.640 +0900 [TRACE] (embulk-output-executor-1): embulk-output-bigquery: record ["2015-07-13", 2015-07-12 15:00:00 UTC, "", 91, "XoALSEQg", 394.5, true]
2018-04-03 10:57:16.665 +0900 [TRACE] (embulk-output-executor-2): embulk-output-bigquery: formatted_record 2015-07-13,2015-07-12 15:00:00.000100 +00:00,"",92,0hgDRI_m,810.9,true
2018-04-03 10:57:16.665 +0900 [TRACE] (embulk-output-executor-1): embulk-output-bigquery: formatted_record 2015-07-13,2015-07-12 15:00:00.000100 +00:00,"",91,XoALSEQg,394.5,true
2018-04-03 10:57:16.665 +0900 [TRACE] (embulk-output-executor-0): embulk-output-bigquery: formatted_record 2015-07-13,2015-07-12 15:00:00.000100 +00:00,"",90,l6lTsvxd,903.4,true
2018-04-03 10:57:16.665 +0900 [TRACE] (embulk-output-executor-3): embulk-output-bigquery: formatted_record 2015-07-13,2015-07-12 15:00:00.000100 +00:00,"",93,KjCRAc-A,477.4,true
2018-04-03 10:57:16.669 +0900 [TRACE] (embulk-output-executor-0): embulk-output-bigquery: record ["2015-07-13", 2015-07-12 15:00:00 UTC, "", 94, "fyQVGlT8", 725.3, true]
2018-04-03 10:57:16.671 +0900 [TRACE] (embulk-output-executor-0): embulk-output-bigquery: formatted_record 2015-07-13,2015-07-12 15:00:00.000100 +00:00,"",94,fyQVGlT8,725.3,true
2018-04-03 10:57:16.681 +0900 [TRACE] (embulk-output-executor-1): embulk-output-bigquery: record ["2015-07-13", 2015-07-12 15:00:00 UTC, "", 95, "FpBYRPWK", 316.6, true]
2018-04-03 10:57:16.682 +0900 [TRACE] (embulk-output-executor-1): embulk-output-bigquery: formatted_record 2015-07-13,2015-07-12 15:00:00.000100 +00:00,"",95,FpBYRPWK,316.6,true
2018-04-03 10:57:16.686 +0900 [TRACE] (embulk-output-executor-2): embulk-output-bigquery: record ["2015-07-13", 2015-07-12 15:00:00 UTC, "", 96, "9ikvnUqp", 369.5, true]
2018-04-03 10:57:16.688 +0900 [TRACE] (embulk-output-executor-2): embulk-output-bigquery: formatted_record 2015-07-13,2015-07-12 15:00:00.000100 +00:00,"",96,9ikvnUqp,369.5,true
2018-04-03 10:57:16.689 +0900 [TRACE] (embulk-output-executor-3): embulk-output-bigquery: record ["2015-07-13", 2015-07-12 15:00:00 UTC, "", 97, "RRNYDAzK", 506.5, true]
2018-04-03 10:57:16.691 +0900 [TRACE] (embulk-output-executor-3): embulk-output-bigquery: formatted_record 2015-07-13,2015-07-12 15:00:00.000100 +00:00,"",97,RRNYDAzK,506.5,true
2018-04-03 10:57:16.697 +0900 [TRACE] (embulk-output-executor-0): embulk-output-bigquery: record ["2015-07-13", 2015-07-12 15:00:00 UTC, "", 90, "l6lTsvxd", 903.4, false]
2018-04-03 10:57:16.699 +0900 [TRACE] (embulk-output-executor-0): embulk-output-bigquery: formatted_record 2015-07-13,2015-07-12 15:00:00.000100 +00:00,"",90,l6lTsvxd,903.4,false
2018-04-03 10:57:16.704 +0900 [TRACE] (embulk-output-executor-1): embulk-output-bigquery: record ["2015-07-13", 2015-07-12 15:00:00 UTC, "", 91, "XoALSEQg", 394.5, false]
2018-04-03 10:57:16.709 +0900 [TRACE] (embulk-output-executor-1): embulk-output-bigquery: formatted_record 2015-07-13,2015-07-12 15:00:00.000100 +00:00,"",91,XoALSEQg,394.5,false
2018-04-03 10:57:16.709 +0900 [TRACE] (embulk-output-executor-2): embulk-output-bigquery: record ["2015-07-13", 2015-07-12 15:00:00 UTC, "", 92, "0hgDRI_m", 810.9, false]
2018-04-03 10:57:16.712 +0900 [TRACE] (embulk-output-executor-2): embulk-output-bigquery: formatted_record 2015-07-13,2015-07-12 15:00:00.000100 +00:00,"",92,0hgDRI_m,810.9,false
2018-04-03 10:57:16.714 +0900 [TRACE] (embulk-output-executor-3): embulk-output-bigquery: record ["2015-07-13", 2015-07-12 15:00:00 UTC, "", 93, "KjCRAc-A", 477.4, false]
2018-04-03 10:57:16.716 +0900 [TRACE] (embulk-output-executor-3): embulk-output-bigquery: formatted_record 2015-07-13,2015-07-12 15:00:00.000100 +00:00,"",93,KjCRAc-A,477.4,false
2018-04-03 10:57:16.717 +0900 [TRACE] (embulk-output-executor-0): embulk-output-bigquery: record ["2015-07-13", 2015-07-12 15:00:00 UTC, "", 94, "fyQVGlT8", 725.3, false]
2018-04-03 10:57:16.719 +0900 [TRACE] (embulk-output-executor-0): embulk-output-bigquery: formatted_record 2015-07-13,2015-07-12 15:00:00.000100 +00:00,"",94,fyQVGlT8,725.3,false
2018-04-03 10:57:16.722 +0900 [TRACE] (embulk-output-executor-1): embulk-output-bigquery: record ["2015-07-13", 2015-07-12 15:00:00 UTC, "", 95, "FpBYRPWK", 316.6, false]
2018-04-03 10:57:16.725 +0900 [TRACE] (embulk-output-executor-2): embulk-output-bigquery: record ["2015-07-13", 2015-07-12 15:00:00 UTC, "", 96, "9ikvnUqp", 369.5, false]
2018-04-03 10:57:16.725 +0900 [TRACE] (embulk-output-executor-1): embulk-output-bigquery: formatted_record 2015-07-13,2015-07-12 15:00:00.000100 +00:00,"",95,FpBYRPWK,316.6,false
2018-04-03 10:57:16.727 +0900 [TRACE] (embulk-output-executor-2): embulk-output-bigquery: formatted_record 2015-07-13,2015-07-12 15:00:00.000100 +00:00,"",96,9ikvnUqp,369.5,false
2018-04-03 10:57:16.729 +0900 [TRACE] (embulk-output-executor-3): embulk-output-bigquery: record ["2015-07-13", 2015-07-12 15:00:00 UTC, "", 97, "RRNYDAzK", 506.5, false]
2018-04-03 10:57:16.731 +0900 [TRACE] (embulk-output-executor-3): embulk-output-bigquery: formatted_record 2015-07-13,2015-07-12 15:00:00.000100 +00:00,"",97,RRNYDAzK,506.5,false
```

**Comment by sonots** [comment] 2018-04-04 15:27
With print debugging at https://github.com/embulk/embulk-output-bigquery/blob/42323298d03a28843f2f0dd1413f315fbe0f4719/lib/embulk/output/bigquery/value_converter_factory.rb#L241

it looks the value itself is right (`val.to_f` #=> 1436713200.1), but 

```
val.strftime("%Y-%m-%d %H:%M:%S.%6N %:z")
```

generates 

```
2015-07-12 15:00:00.000100 +00:00
```

a wrong string. This format string is correct in ruby (CRuby or JRuby), but embulk is working wierd.

I've heard that the embulk timestamp parser/formatter had been changed to work faster, it would be the cause.

**Comment by hiroyuki-sato** [comment] 2018-04-05 11:34
Hello, @kmrshntr 

This isn't plugin specific issue. 
I created https://github.com/embulk/embulk/issues/999

I think this configuration avoid this issue.
https://github.com/embulk/embulk-output-bigquery/#formatter-performance-issue

**Comment by joker1007** [comment] 2018-04-05 12:46
@hiroyuki-sato 
Thanks you very much!!
 I close this issue.

**Closed as completed by joker1007** 2018-04-05 12:46 UTC

**Comment by sakama** [comment] 2018-04-05 15:25
I confirmed this problem can be happened with Embulk 0.8.36+ 😢

**Comment by kmrshntr** [comment] 2018-04-06 01:41
@hiroyuki-sato Thank you for the escalation and helpful workaround method 😂

**Comment by hiroyuki-sato** [comment] 2018-04-10 08:59
@kmrshntr embulk [0.9.6](http://www.embulk.org/docs/release/release-0.9.6.html) has been released. It fixes this issue. Could you try this version when you have a time?

**Comment by kmrshntr** [comment] 2018-07-05 01:22
@hiroyuki-sato Now I tried that new version and confirmed this issue was fixed. Thank you!
